version: '3.9'
services:
  postgres:  
    image: postgres:15-alpine
    ports:
      - 5432:5432
    env_file: ".env"
    volumes:
      - ${POSTGRES_BASE_PATH}:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    
