version: '3.6'
services:
    redis:
        image: redis/redis-stack-server:latest
        ports:
            - '6379:6379'
        healthcheck:
            test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
        env_file:
            - .env
        volumes:
            - ${REDIS_BASE_PATH}/redis_data:/data
        environment:
            - REDIS_ARGS="--requirepass ${REDIS_PASSWORD}"
